name: ramanchada2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python<=3.10
  - mamba
  - pip
  - h5py
  - jupyter
  - lmfit
  - matplotlib
  - numpy
  - pandas
  - pydantic
  - scipy
  - uncertainties
  - pip:
    - -e .

