---
name: Post a coverage report comment on pull requests

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      - 'CI'
    types:
      - 'completed'

jobs:

  comment:

    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      contents: write
      actions: read

    steps:

      - name: Post the stored pull request coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3.27
        with:
          COVERAGE_DATA_BRANCH: 'COVERAGE-REPORT'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
