---
name: docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install tox

      - name: Build docs
        run: |
          tox -e docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
