---
name: Publish Python package to PyPI

on:  # yamllint disable-line rule:truthy
  release:
    types: ['published']

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Store the package distributions
        uses: actions/upload-artifact@v4.6.2
        with:
          if-no-files-found: error
          name: ramanchada2-dist
          overwrite: true
          path: dist
          retention-days: 1

  publish:

    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/ramanchada2
    permissions:
      id-token: write

    steps:

      - name: Retrieve the package distributions
        uses: actions/download-artifact@v4.3.0
        with:
          name: ramanchada2-dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
